env:

  host: localhost
  port: 2000
  map: Town01_Opt
  
  behavior: normal # Cautious, Aggressive, 

  width: 640 
  height: 360

collect:

  max_trajectory: 1000
  max_step: 200

train:
  lr: 1e-4
  path: /home/gav/Desktop/CARLA/Agents/IL/Datasets/Train/
  epoch: 150

test:
  path: /home/gav/Desktop/CARLA/Agents/IL/Datasets/Test/